### ISSUE TITLE
Support the ability to modify templates at runtime.

### ISSUE THREAD

**Issue by Scarafone** [insanoid/SwiftyJSONAccelerator#33]
I think it would be interesting and useful to support the ability to edit templates at runtime.
I think by taking the already in place parameters and creating a simple click and insert interface, you can easily allow the end user to modify the template without having the source.

Further thought:
Maybe include a feature to export custom templates for sharing, based on new paradigms, etc.

**Comment by insanoid** [comment]
The application is suppose to be very minimal simple JSON to Swift code generator. It already allows you to select if you want things like NSCoding support and the JSON parsing library you want to use.

The future version of the app is already a bit more modular allowing anyone to add new libraries to the app without going through the entire codebase but just extending some protocols for their own libraries and adding their template into the project.

Although, I haven't still finished it (due to lack of time), If you want you can have a look here https://github.com/insanoid/SwiftyJSONAccelerator/tree/releases/v1.0 but it is pretty close, the generator module is functional but UI for the app still needs some work.
