### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by jonah-neugass-ck** [insanoid/SwiftyJSONAccelerator#66]
My build is failing with the following error:

```
▸ Copying SwiftyJSONAccelerator/Templates/BaseTemplate.txt
▸ Copying SwiftyJSONAccelerator/Templates/Library-Extension-Templates/MarshalTemplate.txt
▸ Generating 'SwiftyJSONAccelerator.app.dSYM'
▸ Running script 'SwiftLint'
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution SwiftLint /Users/jonah.neugass/Library/Developer/Xcode/DerivedData/SwiftyJSONAccelerator-bcwgjtlsrftxmvdldjpdtlzwhrfb/Build/Intermediates/SwiftyJSONAccelerator.build/Release/SwiftyJSONAccelerator.build/Script-930462B91D311F9100FE61A6.sh
(1 failure)
 ✓ SwiftyJSONAccelerator app and CLI successfully installed!! 🍻
 ✓ Use the app from Applications or ./swiftyjsonaccelerator
```

Platform: Sierra 10.12.4
Xcode: 8.3.2

**Comment by insanoid** [comment]
It is failing because the code no longer adheres to the SwiftLint check (because of some change in the lint in the recent version), I have not updated the app in a while.

I am working on a new version with support for newer swift version/libraries. In the meanwhile, you can open the project in Xcode and remove SwiftLint script in the target's build phase.

Hope that makes sense!
