### ISSUE TITLE
App Installation with CLI Failed

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [insanoid/SwiftyJSONAccelerator#70]
Hi,

I think this library was so great that helps developers to create their models in an instant, that is why I want to try this but unfortunately I am stuck in the installation with CLI. Please see the image below.

I am just following the steps, and even I add sudo in the make install same error occurs. I am also newbie in linux.

Hope anyone can help me.

Thank you.

<img width="696" alt="screen shot 2017-06-09 at 8 37 33 am" src="https://user-images.githubusercontent.com/5118009/26956257-f0b898bc-4cee-11e7-9fd0-b7d17aaea741.png">

**Comment by insanoid** [comment]
The issue is due to permission denied while trying to execute `bundle install`, i think you should look into it - https://stackoverflow.com/questions/17959435/bundle-install-failed-due-to-permission-denied here is something to start with.

Worst case scenario, edit the [Makefile](https://github.com/insanoid/SwiftyJSONAccelerator/blob/master/Makefile) to run the command it with `sudo` however I recommend fixing the Ruby problem.
